# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
   config.vm.box = "base"
   config.vm.network "public_network"
   config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "512"
   end
end
